version: 0.2

phases:

  install:
    runtime-versions:
      nodejs: 14

  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build
      
  post_build:
    commands:
      - echo Coping to S3
      - aws s3 cp --recursive  ./build s3://codebuilds2908/ 
      
artifacts:
   files:
     - '**/*'
